## Numpy

### NumPy is a core Python library used for numerical computing. If you're moving toward Data Analytics, NumPy is foundational because almost every data library (like Pandas, SciPy, Scikit-learn) is built on top of it.

## 1️⃣ Why NumPy is Important

### In normal Python:

- ### Lists are slower for mathematical operations.

- ### No built-in support for vectorized computation.

### NumPy provides:

- ### ✅ Fast multidimensional arrays

- ### ✅ Vectorized operations (no loops required)

- ### ✅ Mathematical, statistical & linear algebra functions

- ### ✅ Efficient memory usage

In [1]:
import numpy as np

In [2]:
# 1D Array

arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)
print(type(arr1))
print(arr1.shape)

print(arr1.reshape(1, 5))
print(arr1.reshape(5, 1)) 

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
# 2D Array

arr2 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])

print(arr2)
print(arr2.shape)


[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [11]:
np.arange(0, 10, 2).reshape(1, 5)

array([[0, 2, 4, 6, 8]])

In [6]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
# Identity Matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Properties in Numpy

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size (number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


## Numpy Vectorized Operations

In [21]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element Wise Addition

print(f"Addition : {arr1 + arr2}")

# Element Wise Subtraction

print(f"Subtraction: {arr1 - arr2}")

# Element Wise Multiplication

print(f"Multiplication: {arr1 * arr2}")

# Element Wise Division

print(f"Division: {arr1 / arr2}")

Addition : [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


## Universal Functions

### - sqrt()
### - exp()
### - sin()
### - log()

In [25]:
# Square of array elements
arr = np.array([2, 3, 4, 5, 6])
print(np.sqrt(arr))

# Exponentiation
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Log

print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


## Array Slicing and Indexing

In [2]:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array: \n", arr)

# Indexing

print(arr[0, 3])
print(arr[2][3])

# Slicing

# Only Rows
print(arr[2:])
print(arr[1:])

# Rows and Columns

print(arr[1:, 2:])
print(arr[0:2, 2:])

print(arr[1:, 1:3])

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
4
12
[[ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


## Modifying Array Elements

In [9]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

arr[0][3] = 50

arr[2, 1] = 100

print(arr)

[[  1   2   3  50]
 [  5   6   7   8]
 [  9 100  11  12]]


## Numpy Mathematical Operations

### - mean()
### - median()
### - std()
### - var()

In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
print("Mean:", np.mean(arr))

# Median
print("Median:", np.median(arr))

# Standard Deviation
print("Standard Deviation:", np.std(arr))

# Variance
print("Variance:", np.var(arr))

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [4]:
# Logical Operations

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr > 5)

print(arr[arr > 5])

print(arr[(arr > 5) & (arr < 8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[6 7]
